# Generated by Django 5.2.11 on 2026-02-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
